### ISSUE TITLE
Проблема в файле autoload.php

### ISSUE THREAD

**Issue by oleglavrik** [padp/php_modern_design_patterns#1]
Суть проблемы: 
Parse error: syntax error, unexpected '[', expecting ')' 

public function __construct()
{
     spl_autoload_register([$this, 'loader']);
}
Постараюсь разобраться сам, но от помощи не откажусь, junior пока

**Comment by oleglavrik** [comment]
Думаю есть решение проблемы:
public function __construct()
{
       spl_autoload_register(array($this, 'loader'));
}
Нужно явно указать что передается массив, у меня все заработало.

**Comment by padp** [comment]
[$this, 'loader'] - это сокращённая нотация для массива, поддерживается начиная с php 5.4

**Comment by oleglavrik** [comment]
Думаю надо добавить коментарий для тех кто еще использует php 5.3
# for php 5.3  spl_autoload_register(array($this, 'loader'));
Вопрос: Не устарела ли php 5.3 и нужно ли переходить на php 5.4/5.5 ?

**Comment by padp** [comment]
Не то что она устарела, а она вообще как динозавр уже, срочно обновляй

**Comment by padp** [comment]
Не то что она устарела, а она вообще уже динозавр, срочно обновляйся до 5.5.
